name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    env:
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
      MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Decode service account and create file
      env:
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
      run: |
          echo $SERVICE_ACCOUNT_JSON_BASE64 | base64 --decode > service_account.json

    - name: Build Docker image
      run: |
        docker build 
        --build-arg GMAIL_PASS=${{ secrets.GMAIL_PASS }} \
                     --build-arg MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} \
                     --build-arg MONGO_DB_HOST=${{ secrets.MONGO_DB_HOST }} \
                     --build-arg MONGO_DB_USER=${{ secrets.MONGO_DB_USER }} \
                     --build-arg MONGO_PASS=${{ secrets.MONGO_PASS}} \
                     -t jahanzaibbaig111/fyp .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build \
          --build-arg GMAIL_PASS=${{ secrets.GMAIL_PASS }} \
          --build-arg MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} \
          --build-arg MONGO_DB_HOST=${{ secrets.MONGO_DB_HOST }} \
          --build-arg MONGO_DB_USER=${{ secrets.MONGO_DB_USER }} \
          --build-arg MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }} \
          -t jahanzaibbaig111/fyp .

    - name: Push Docker image to Docker Hub
      run: |
        docker push jahanzaibbaig111/fyp
